var arbeidsforholdData = [
  {
    "Id": 4426,
    "Fornavn": "Aqeel",
    "Etternavn": "Cueto",
    "Kjonn": "Mann",
    "Alder": 35,
    "ArbStedNr": "63420000",
    "Arbeidsted": "Knarvik vgs - Adm.stab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "655921",
    "Stillingsbeskrivelse": "Ikt-konsulent i",
    "ArsLonn": 387000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4446,
    "Fornavn": "Jolinn",
    "Etternavn": "Mengistu",
    "Kjonn": "Kvinne",
    "Alder": 39,
    "ArbStedNr": "65750000",
    "Arbeidsted": "Hjeltnes vgs - Avd. Hagebruk",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "751705",
    "Stillingsbeskrivelse": "Gartnar/annleggsgartnar m/fagb",
    "ArsLonn": 358800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 75.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4452,
    "Fornavn": "Tor",
    "Etternavn": "Fretheim",
    "Kjonn": "Mann",
    "Alder": 67,
    "ArbStedNr": "40070000",
    "Arbeidsted": "Kunst- og kulturformidling - Kultur- og idrettsavd.",
    "ArbfNr": 1,
    "Ansattforhold": "Engasjement",
    "Stillingskode": "999900",
    "Stillingsbeskrivelse": "Diverse                       ",
    "ArsLonn": 1.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4461,
    "Fornavn": "Fillip",
    "Etternavn": "Becke",
    "Kjonn": "Mann",
    "Alder": 33,
    "ArbStedNr": "62230000",
    "Arbeidsted": "Bergen Handelsgymnasium - Avd. Øko. og Samf. fag.",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "796311",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning i",
    "ArsLonn": 424300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 60.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4467,
    "Fornavn": "Beatrix",
    "Etternavn": "Nordvold",
    "Kjonn": "Kvinne",
    "Alder": 26,
    "ArbStedNr": "62190000",
    "Arbeidsted": "DIVERSE - Bergen Katedralskole",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796000",
    "Stillingsbeskrivelse": "Lærer u/godkj.utdannelse",
    "ArsLonn": 302700.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4471,
    "Fornavn": "Norlys",
    "Etternavn": "Baldursson",
    "Kjonn": "Kvinne",
    "Alder": 50,
    "ArbStedNr": "5005000108",
    "Arbeidsted": "THD. Vest, Sælen",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "710000",
    "Stillingsbeskrivelse": "Tannhelsesekretær",
    "ArsLonn": 358800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 40.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4474,
    "Fornavn": "Julia Yan",
    "Etternavn": "Fleten",
    "Kjonn": "Kvinne",
    "Alder": 22,
    "ArbStedNr": "62080000",
    "Arbeidsted": "DIVERSE - Langhaugen vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796000",
    "Stillingsbeskrivelse": "Lærer u/godkj.utdannelse",
    "ArsLonn": 302700.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4475,
    "Fornavn": "Jurij",
    "Etternavn": "Elvik",
    "Kjonn": "Mann",
    "Alder": 61,
    "ArbStedNr": "61240000",
    "Arbeidsted": "Fana gymnas - Avd. Realfag/Kr.øving",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796611",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd. i",
    "ArsLonn": 555100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4476,
    "Fornavn": "Maine",
    "Etternavn": "Klungeland",
    "Kjonn": "Kvinne",
    "Alder": 43,
    "ArbStedNr": "62660000",
    "Arbeidsted": "Sandsli vgs - Avd. Realfag/Økon.fag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 494500.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4479,
    "Fornavn": "Joaqvin",
    "Etternavn": "Breien",
    "Kjonn": "Mann",
    "Alder": 66,
    "ArbStedNr": "63050000",
    "Arbeidsted": "Kvinnherad vgs - Avd. Studspes/Fellesfag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 555100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 60.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4482,
    "Fornavn": "Raziye",
    "Etternavn": "Abild",
    "Kjonn": "Kvinne",
    "Alder": 55,
    "ArbStedNr": "5005000100",
    "Arbeidsted": "THD. Vest, Loddefjord",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "710000",
    "Stillingsbeskrivelse": "Tannhelsesekretær",
    "ArsLonn": 358800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 50.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4484,
    "Fornavn": "Øzlem",
    "Etternavn": "Størset",
    "Kjonn": "Kvinne",
    "Alder": 29,
    "ArbStedNr": "61140000",
    "Arbeidsted": "Os gymnas - Avd. Språk/Samf./Økonomi",
    "ArbfNr": 2,
    "Ansattforhold": "Fast",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 428800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 99.89,
    "KravTilbut": "False"
  },
  {
    "Id": 4487,
    "Fornavn": "Ellisiv",
    "Etternavn": "Krokan",
    "Kjonn": "Kvinne",
    "Alder": 35,
    "ArbStedNr": "62230000",
    "Arbeidsted": "Bergen Handelsgymnasium - Avd. Øko. og Samf. fag.",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 413900.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 57.27,
    "KravTilbut": "False"
  },
  {
    "Id": 4492,
    "Fornavn": "Florida",
    "Etternavn": "Thevamalar",
    "Kjonn": "Kvinne",
    "Alder": 50,
    "ArbStedNr": "62820000",
    "Arbeidsted": "Odda vgs - Adm. stab (Adm/IKT/Reinhald)",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "700306",
    "Stillingsbeskrivelse": "Kantinebestyrar m/fagbrev",
    "ArsLonn": 344000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 50.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4495,
    "Fornavn": "Rosanna",
    "Etternavn": "Holmestad",
    "Kjonn": "Kvinne",
    "Alder": 32,
    "ArbStedNr": "61740000",
    "Arbeidsted": "Tertnes vgs - Stab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "752000",
    "Stillingsbeskrivelse": "Førstesekretær",
    "ArsLonn": 359000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 60.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4502,
    "Fornavn": "Palma",
    "Etternavn": "Thomasstuen",
    "Kjonn": "Mann",
    "Alder": 57,
    "ArbStedNr": "40060000",
    "Arbeidsted": "Kulturminnevern og museum - Kultur- og idrettsavd.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "703700",
    "Stillingsbeskrivelse": "Byggeleder                    ",
    "ArsLonn": 370000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 30.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4507,
    "Fornavn": "Riikka",
    "Etternavn": "Mwanga",
    "Kjonn": "Kvinne",
    "Alder": 45,
    "ArbStedNr": "63320000",
    "Arbeidsted": "Slåtthaug vgs - Adm.stab (Drift)",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "655901",
    "Stillingsbeskrivelse": "Førstekonsulent          ",
    "ArsLonn": 402000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4512,
    "Fornavn": "Normann",
    "Etternavn": "Laskemoen",
    "Kjonn": "Mann",
    "Alder": 48,
    "ArbStedNr": "63150000",
    "Arbeidsted": "Rubbestadneset vgs - Avd. Elektro",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4516,
    "Fornavn": "Torfinn",
    "Etternavn": "Tyskberg",
    "Kjonn": "Mann",
    "Alder": 61,
    "ArbStedNr": "64460000",
    "Arbeidsted": "Fusa vgs - Avd. FF/NA/FO/TP",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4525,
    "Fornavn": "Otmane",
    "Etternavn": "Mabrouki",
    "Kjonn": "Mann",
    "Alder": 58,
    "ArbStedNr": "65940000",
    "Arbeidsted": "Voss jbs - Avd. Skule ped.pers.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 80.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4527,
    "Fornavn": "Wanida",
    "Etternavn": "Sithamparan",
    "Kjonn": "Kvinne",
    "Alder": 52,
    "ArbStedNr": "5006000100",
    "Arbeidsted": "THD. Sør, Rosendal",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "830100",
    "Stillingsbeskrivelse": "Tannlege",
    "ArsLonn": 633000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 87.30,
    "KravTilbut": "False"
  },
  {
    "Id": 4531,
    "Fornavn": "Ibtisam",
    "Etternavn": "Stine",
    "Kjonn": "Kvinne",
    "Alder": 43,
    "ArbStedNr": "3006000200",
    "Arbeidsted": "Administrasjon - Skyss",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "853001",
    "Stillingsbeskrivelse": "Spesialrådgjevar          ",
    "ArsLonn": 435000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4535,
    "Fornavn": "Torstein",
    "Etternavn": "Dahle",
    "Kjonn": "Mann",
    "Alder": 26,
    "ArbStedNr": "66592000",
    "Arbeidsted": "DIVERSE - Stord vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796000",
    "Stillingsbeskrivelse": "Lærer u/godkj.utdannelse",
    "ArsLonn": 298200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4538,
    "Fornavn": "Kersti",
    "Etternavn": "Gamman",
    "Kjonn": "Kvinne",
    "Alder": 57,
    "ArbStedNr": "61830000",
    "Arbeidsted": "Tanks vgs - Fagstab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796611",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd. i",
    "ArsLonn": 555100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4542,
    "Fornavn": "Sivert",
    "Etternavn": "Thorsteinsson",
    "Kjonn": "Mann",
    "Alder": 36,
    "ArbStedNr": "61850000",
    "Arbeidsted": "Tanks vgs - Avd. språk og samfunnsfag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796611",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd. i",
    "ArsLonn": 459700.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4549,
    "Fornavn": "Lloyd",
    "Etternavn": "Røineland",
    "Kjonn": "Mann",
    "Alder": 40,
    "ArbStedNr": "63260000",
    "Arbeidsted": "Voss vgs - Avd. Granvin",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796100",
    "Stillingsbeskrivelse": "Lærer",
    "ArsLonn": 391000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4552,
    "Fornavn": "Muhamed",
    "Etternavn": "Stareng",
    "Kjonn": "Mann",
    "Alder": 61,
    "ArbStedNr": "64260000",
    "Arbeidsted": "Bergen Tekn. Fag. - Avd. Elektro og prosess",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 555100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 26.55,
    "KravTilbut": "False"
  },
  {
    "Id": 4560,
    "Fornavn": "Kristi",
    "Etternavn": "Nyfelt",
    "Kjonn": "Kvinne",
    "Alder": 35,
    "ArbStedNr": "64460000",
    "Arbeidsted": "Fusa vgs - Avd. FF/NA/FO/TP",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 438300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4564,
    "Fornavn": "Zahid",
    "Etternavn": "Hefte",
    "Kjonn": "Mann",
    "Alder": 36,
    "ArbStedNr": "61860000",
    "Arbeidsted": "DIVERSE - Tanks vgs",
    "ArbfNr": 2,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796100",
    "Stillingsbeskrivelse": "Lærer",
    "ArsLonn": 364000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4572,
    "Fornavn": "Anwar",
    "Etternavn": "Lauknes",
    "Kjonn": "Mann",
    "Alder": 66,
    "ArbStedNr": "61450000",
    "Arbeidsted": "Voss gymnas - Avd. Studiespesialiserande",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796611",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd. i",
    "ArsLonn": 555100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 60.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4576,
    "Fornavn": "Zerom",
    "Etternavn": "Rafoss",
    "Kjonn": "Mann",
    "Alder": 35,
    "ArbStedNr": "64650000",
    "Arbeidsted": "Os vgs - Avd. TIP/Elektro",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796100",
    "Stillingsbeskrivelse": "Lærer",
    "ArsLonn": 391000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4581,
    "Fornavn": "Bavan",
    "Etternavn": "Falsen",
    "Kjonn": "Mann",
    "Alder": 58,
    "ArbStedNr": "65860000",
    "Arbeidsted": "Stend vgs - Avd. Naturbruk",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796100",
    "Stillingsbeskrivelse": "Lærer",
    "ArsLonn": 435200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 60.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4585,
    "Fornavn": "Attiq",
    "Etternavn": "Abdulahi",
    "Kjonn": "Mann",
    "Alder": 48,
    "ArbStedNr": "63970000",
    "Arbeidsted": "Årstad vgs - Avd. Service",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4587,
    "Fornavn": "Linus",
    "Etternavn": "Hamrebø",
    "Kjonn": "Mann",
    "Alder": 59,
    "ArbStedNr": "65040000",
    "Arbeidsted": "Voss hfs - Avd. Ped.personale",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 555100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4591,
    "Fornavn": "Andreas T",
    "Etternavn": "Engelsen",
    "Kjonn": "Mann",
    "Alder": 27,
    "ArbStedNr": "66592000",
    "Arbeidsted": "DIVERSE - Stord vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796000",
    "Stillingsbeskrivelse": "Lærer u/godkj.utdannelse",
    "ArsLonn": 307000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4598,
    "Fornavn": "Anstein",
    "Etternavn": "Huggins",
    "Kjonn": "Mann",
    "Alder": 56,
    "ArbStedNr": "66591000",
    "Arbeidsted": "Stord vgs - Avd. Opplæringssenteret",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4600,
    "Fornavn": "Mahmood",
    "Etternavn": "Kaberg",
    "Kjonn": "Mann",
    "Alder": 54,
    "ArbStedNr": "1306000215",
    "Arbeidsted": "Driftsområde - 15 Kvam",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "700301",
    "Stillingsbeskrivelse": "Driftsleder m/fagbrev    ",
    "ArsLonn": 372800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4605,
    "Fornavn": "Merry",
    "Etternavn": "Rama",
    "Kjonn": "Kvinne",
    "Alder": 28,
    "ArbStedNr": "65750000",
    "Arbeidsted": "Hjeltnes vgs - Avd. Hagebruk",
    "ArbfNr": 1,
    "Ansattforhold": "Engasjement",
    "Stillingskode": "601400",
    "Stillingsbeskrivelse": "Arbeidar",
    "ArsLonn": 282200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4611,
    "Fornavn": "Halgrim",
    "Etternavn": "Glørud",
    "Kjonn": "Mann",
    "Alder": 60,
    "ArbStedNr": "63940000",
    "Arbeidsted": "Årstad vgs - Avd. Teknologi",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4616,
    "Fornavn": "Eivind",
    "Etternavn": "Goba",
    "Kjonn": "Mann",
    "Alder": 58,
    "ArbStedNr": "50010000",
    "Arbeidsted": "TANNHELSEAVDELINGA",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "945009",
    "Stillingsbeskrivelse": "Fylkestannlege           ",
    "ArsLonn": 793000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4619,
    "Fornavn": "Tarek",
    "Etternavn": "Skrindo",
    "Kjonn": "Mann",
    "Alder": 47,
    "ArbStedNr": "5004000103",
    "Arbeidsted": "THD. Nord, Bergen Fengsel",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "830100",
    "Stillingsbeskrivelse": "Tannlege",
    "ArsLonn": 589000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 50.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4626,
    "Fornavn": "Sonny",
    "Etternavn": "Ribu",
    "Kjonn": "Kvinne",
    "Alder": 42,
    "ArbStedNr": "5004000108",
    "Arbeidsted": "THD. Nord, Osterøy",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "710000",
    "Stillingsbeskrivelse": "Tannhelsesekretær",
    "ArsLonn": 358800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 80.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4629,
    "Fornavn": "Eline",
    "Etternavn": "Kirkeng",
    "Kjonn": "Kvinne",
    "Alder": 54,
    "ArbStedNr": "5003000103",
    "Arbeidsted": "THD. Sentrum, Haukeland",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "717500",
    "Stillingsbeskrivelse": "Tannpleier",
    "ArsLonn": 402000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 50.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4632,
    "Fornavn": "Børge",
    "Etternavn": "Rydenbàck",
    "Kjonn": "Mann",
    "Alder": 22,
    "ArbStedNr": "636110000",
    "Arbeidsted": "DIVERSE - Laksevåg vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønn",
    "Stillingskode": "657201",
    "Stillingsbeskrivelse": "Miljøassistent",
    "ArsLonn": 262100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4640,
    "Fornavn": "Shari",
    "Etternavn": "Abdelhafiz",
    "Kjonn": "Kvinne",
    "Alder": 39,
    "ArbStedNr": "66020000",
    "Arbeidsted": "Etne vgs - Stab",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "795401",
    "Stillingsbeskrivelse": "Elevinspektør            ",
    "ArsLonn": 564200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4644,
    "Fornavn": "Nagham",
    "Etternavn": "Kyllingstad",
    "Kjonn": "Kvinne",
    "Alder": 61,
    "ArbStedNr": "62270000",
    "Arbeidsted": "DIVERSE - Bergen Handelsgymnasium",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønn",
    "Stillingskode": "721000",
    "Stillingsbeskrivelse": "Renholder",
    "ArsLonn": 338300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 66.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4649,
    "Fornavn": "Ingerid",
    "Etternavn": "Grønningsæter",
    "Kjonn": "Kvinne",
    "Alder": 28,
    "ArbStedNr": "61710000",
    "Arbeidsted": "TERTNES VGS",
    "ArbfNr": 2,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796311",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning i",
    "ArsLonn": 413900.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4653,
    "Fornavn": "Ingerid",
    "Etternavn": "Grønningsæter",
    "Kjonn": "Kvinne",
    "Alder": 28,
    "ArbStedNr": "61220000",
    "Arbeidsted": "Fana gymnas - Avd. Samf./Øko./Fr.språk",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 413900.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 72.80,
    "KravTilbut": "False"
  },
  {
    "Id": 4656,
    "Fornavn": "Torgeir",
    "Etternavn": "Ims",
    "Kjonn": "Mann",
    "Alder": 45,
    "ArbStedNr": "63150000",
    "Arbeidsted": "Rubbestadneset vgs - Avd. Elektro",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 474900.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4660,
    "Fornavn": "Amrit",
    "Etternavn": "Bukurije",
    "Kjonn": "Mann",
    "Alder": 66,
    "ArbStedNr": "1306000207",
    "Arbeidsted": "Driftsområde - 7 Bergen sentrum ",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "659200",
    "Stillingsbeskrivelse": "Avdelingsleder                ",
    "ArsLonn": 434200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 80.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4664,
    "Fornavn": "Moria",
    "Etternavn": "Hanche",
    "Kjonn": "Kvinne",
    "Alder": 42,
    "ArbStedNr": "62830000",
    "Arbeidsted": "Odda vgs - Avd. Studiespesialiserande/Idrett",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4667,
    "Fornavn": "Kyrre",
    "Etternavn": "Sraanes",
    "Kjonn": "Mann",
    "Alder": 38,
    "ArbStedNr": "65560000",
    "Arbeidsted": "Bergen Maritime vgs - Avd. Elektro og Mekanisk",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4676,
    "Fornavn": "Paulina",
    "Etternavn": "Vaskinn",
    "Kjonn": "Kvinne",
    "Alder": 51,
    "ArbStedNr": "62830000",
    "Arbeidsted": "Odda vgs - Avd. Studiespesialiserande/Idrett",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796311",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning i",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4679,
    "Fornavn": "Abede",
    "Etternavn": "Lindstølen",
    "Kjonn": "Mann",
    "Alder": 28,
    "ArbStedNr": "64590000",
    "Arbeidsted": "DIVERSE - Sotra vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796100",
    "Stillingsbeskrivelse": "Lærer",
    "ArsLonn": 355100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4683,
    "Fornavn": "Hadish",
    "Etternavn": "Albåge",
    "Kjonn": "Mann",
    "Alder": 64,
    "ArbStedNr": "65560000",
    "Arbeidsted": "Bergen Maritime vgs - Avd. Elektro og Mekanisk",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796311",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning i",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4684,
    "Fornavn": "Samuel",
    "Etternavn": "Tonby",
    "Kjonn": "Mann",
    "Alder": 60,
    "ArbStedNr": "66560000",
    "Arbeidsted": "Stord vgs - Avd. ID/MDD",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796311",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning i",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4689,
    "Fornavn": "Marjo",
    "Etternavn": "Svendsen",
    "Kjonn": "Kvinne",
    "Alder": 39,
    "ArbStedNr": "5005000103",
    "Arbeidsted": "THD. Vest, Kleppestø",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "830100",
    "Stillingsbeskrivelse": "Tannlege",
    "ArsLonn": 554000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 75.95,
    "KravTilbut": "False"
  },
  {
    "Id": 4692,
    "Fornavn": "Juana",
    "Etternavn": "Pederstad",
    "Kjonn": "Kvinne",
    "Alder": 39,
    "ArbStedNr": "66330000",
    "Arbeidsted": "Nordahl Grieg vgs - Avd. Stud.spes 1",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 494500.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4696,
    "Fornavn": "Therese",
    "Etternavn": "Sønmez",
    "Kjonn": "Kvinne",
    "Alder": 56,
    "ArbStedNr": "64520000",
    "Arbeidsted": "Sotra vgs - Driftsstab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "721000",
    "Stillingsbeskrivelse": "Renholder",
    "ArsLonn": 338300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 68.74,
    "KravTilbut": "False"
  },
  {
    "Id": 4698,
    "Fornavn": "Halldis",
    "Etternavn": "Fagermo",
    "Kjonn": "Kvinne",
    "Alder": 43,
    "ArbStedNr": "66020000",
    "Arbeidsted": "Etne vgs - Stab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "752000",
    "Stillingsbeskrivelse": "Førstesekretær",
    "ArsLonn": 359000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 80.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4701,
    "Fornavn": "Noroz",
    "Etternavn": "Sandvei",
    "Kjonn": "Mann",
    "Alder": 48,
    "ArbStedNr": "63980000",
    "Arbeidsted": "Årstad vgs - Avd. Byggfag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4705,
    "Fornavn": "Oddrunn",
    "Etternavn": "Moayeri",
    "Kjonn": "Kvinne",
    "Alder": 57,
    "ArbStedNr": "6388000100",
    "Arbeidsted": "Åsane vgs - Avd. BF",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796311",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning i",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 75.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4706,
    "Fornavn": "Vigmund",
    "Etternavn": "Rudsli",
    "Kjonn": "Mann",
    "Alder": 43,
    "ArbStedNr": "61460000",
    "Arbeidsted": "Voss gymnas - Avd. Idrett/Toppidrett",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 40.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4708,
    "Fornavn": "Truls",
    "Etternavn": "Kingsrød",
    "Kjonn": "Mann",
    "Alder": 33,
    "ArbStedNr": "61840000",
    "Arbeidsted": "Tanks vgs - Avd. realfag og øk.fag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 459700.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 76.51,
    "KravTilbut": "False"
  },
  {
    "Id": 4711,
    "Fornavn": "Benyam",
    "Etternavn": "Borthen",
    "Kjonn": "Mann",
    "Alder": 23,
    "ArbStedNr": "64330000",
    "Arbeidsted": "Askøy vgs - YF II",
    "ArbfNr": 2,
    "Ansattforhold": "Timelønn",
    "Stillingskode": "657201",
    "Stillingsbeskrivelse": "Miljøassistent",
    "ArsLonn": 262100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4715,
    "Fornavn": "Karine",
    "Etternavn": "Kühn",
    "Kjonn": "Kvinne",
    "Alder": 32,
    "ArbStedNr": "61740000",
    "Arbeidsted": "Tertnes vgs - Stab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "657201",
    "Stillingsbeskrivelse": "Miljøassistent",
    "ArsLonn": 328300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 63.50,
    "KravTilbut": "False"
  },
  {
    "Id": 4717,
    "Fornavn": "Tommy",
    "Etternavn": "Sachse",
    "Kjonn": "Mann",
    "Alder": 58,
    "ArbStedNr": "63040000",
    "Arbeidsted": "Kvinnherad vgs - Avd. Spesialund.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4721,
    "Fornavn": "Betsy",
    "Etternavn": "Norderud",
    "Kjonn": "Kvinne",
    "Alder": 50,
    "ArbStedNr": "63940000",
    "Arbeidsted": "Årstad vgs - Avd. Teknologi",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 80.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4725,
    "Fornavn": "Mariel",
    "Etternavn": "Barhoon",
    "Kjonn": "Kvinne",
    "Alder": 48,
    "ArbStedNr": "61740000",
    "Arbeidsted": "Tertnes vgs - Stab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "657201",
    "Stillingsbeskrivelse": "Miljøassistent",
    "ArsLonn": 338300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 89.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4727,
    "Fornavn": "Tijani",
    "Etternavn": "Sundve",
    "Kjonn": "Mann",
    "Alder": 63,
    "ArbStedNr": "60050000",
    "Arbeidsted": "Fagopplæringskontoret - OPPL.AVD.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "853002",
    "Stillingsbeskrivelse": "Seniorrådgjevar          ",
    "ArsLonn": 463000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4729,
    "Fornavn": "Hjalmar",
    "Etternavn": "Løver",
    "Kjonn": "Mann",
    "Alder": 46,
    "ArbStedNr": "65560000",
    "Arbeidsted": "Bergen Maritime vgs - Avd. Elektro og Mekanisk",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 469200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4731,
    "Fornavn": "Else",
    "Etternavn": "Indrevåg",
    "Kjonn": "Kvinne",
    "Alder": 27,
    "ArbStedNr": "62190000",
    "Arbeidsted": "DIVERSE - Bergen Katedralskole",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 395900.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4734,
    "Fornavn": "Iljen",
    "Etternavn": "Heby",
    "Kjonn": "Kvinne",
    "Alder": 36,
    "ArbStedNr": "66130000",
    "Arbeidsted": "Olsvikåsen vgs - Avd. tilrettelagt opplæring",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "751706",
    "Stillingsbeskrivelse": "Miljøfagarbeidar",
    "ArsLonn": 358800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 80.10,
    "KravTilbut": "False"
  },
  {
    "Id": 4736,
    "Fornavn": "Genette",
    "Etternavn": "Dyrud",
    "Kjonn": "Kvinne",
    "Alder": 61,
    "ArbStedNr": "61430000",
    "Arbeidsted": "Voss gymnas - Adm.stab (Merkantil)",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "655900",
    "Stillingsbeskrivelse": "Konsulent",
    "ArsLonn": 369000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4740,
    "Fornavn": "Imran",
    "Etternavn": "Sætre",
    "Kjonn": "Mann",
    "Alder": 53,
    "ArbStedNr": "63970000",
    "Arbeidsted": "Årstad vgs - Avd. Service",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796611",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd. i",
    "ArsLonn": 555100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 60.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4744,
    "Fornavn": "Britta",
    "Etternavn": "Åsdal",
    "Kjonn": "Kvinne",
    "Alder": 54,
    "ArbStedNr": "61420000",
    "Arbeidsted": "Voss gymnas - Fagstab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "795401",
    "Stillingsbeskrivelse": "Elevinspektør            ",
    "ArsLonn": 574700.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4745,
    "Fornavn": "Venche",
    "Etternavn": "Rudsli",
    "Kjonn": "Kvinne",
    "Alder": 59,
    "ArbStedNr": "63450000",
    "Arbeidsted": "Knarvik vgs - Avd. KUP",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "657201",
    "Stillingsbeskrivelse": "Miljøassistent",
    "ArsLonn": 338300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 83.06,
    "KravTilbut": "False"
  },
  {
    "Id": 4748,
    "Fornavn": "Bharat",
    "Etternavn": "Lingstad",
    "Kjonn": "Mann",
    "Alder": 64,
    "ArbStedNr": "65050000",
    "Arbeidsted": "DIVERSE - Voss hfs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 541300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4752,
    "Fornavn": "Gerardo",
    "Etternavn": "Leksås",
    "Kjonn": "Mann",
    "Alder": 44,
    "ArbStedNr": "63470000",
    "Arbeidsted": "Knarvik vgs - Avd. HUM",
    "ArbfNr": 3,
    "Ansattforhold": "Vikar",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 424300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 54.28,
    "KravTilbut": "False"
  },
  {
    "Id": 4754,
    "Fornavn": "Anita Sylta",
    "Etternavn": "Mørner",
    "Kjonn": "Kvinne",
    "Alder": 45,
    "ArbStedNr": "61740000",
    "Arbeidsted": "Tertnes vgs - Stab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "657205",
    "Stillingsbeskrivelse": "Kantineassistent         ",
    "ArsLonn": 328300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 29.66,
    "KravTilbut": "False"
  },
  {
    "Id": 4756,
    "Fornavn": "Zerufi",
    "Etternavn": "Hustadnes",
    "Kjonn": "Mann",
    "Alder": 56,
    "ArbStedNr": "64240000",
    "Arbeidsted": "Bergen Tekn. Fag. - Avd. STO/FIH/Mester",
    "ArbfNr": 2,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 433200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4759,
    "Fornavn": "Zerufi",
    "Etternavn": "Hustadnes",
    "Kjonn": "Mann",
    "Alder": 56,
    "ArbStedNr": "64570000",
    "Arbeidsted": "Sotra vgs - BA/HS",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796100",
    "Stillingsbeskrivelse": "Lærer",
    "ArsLonn": 435200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4762,
    "Fornavn": "Rella",
    "Etternavn": "Elmi",
    "Kjonn": "Kvinne",
    "Alder": 40,
    "ArbStedNr": "63080000",
    "Arbeidsted": "DIVERSE - Kvinnherad vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 424300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4765,
    "Fornavn": "Cille",
    "Etternavn": "Vestbø",
    "Kjonn": "Kvinne",
    "Alder": 61,
    "ArbStedNr": "64860000",
    "Arbeidsted": "DIVERSE - Austevoll vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796000",
    "Stillingsbeskrivelse": "Lærer u/godkj.utdannelse",
    "ArsLonn": 358800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4768,
    "Fornavn": "Alicia",
    "Etternavn": "Hillesund",
    "Kjonn": "Kvinne",
    "Alder": 32,
    "ArbStedNr": "66120000",
    "Arbeidsted": "Olsvikåsen vgs - Adm.stab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "811200",
    "Stillingsbeskrivelse": "Spesialbibliotekar",
    "ArsLonn": 371000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4772,
    "Fornavn": "Andres",
    "Etternavn": "Dåbu",
    "Kjonn": "Mann",
    "Alder": 51,
    "ArbStedNr": "62040000",
    "Arbeidsted": "Langhaugen vgs - Avd. Musikk/Dans",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 555100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 31.07,
    "KravTilbut": "False"
  },
  {
    "Id": 4779,
    "Fornavn": "Dorit",
    "Etternavn": "Foldøy",
    "Kjonn": "Kvinne",
    "Alder": 66,
    "ArbStedNr": "61450000",
    "Arbeidsted": "Voss gymnas - Avd. Studiespesialiserande",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 555100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4782,
    "Fornavn": "Terry",
    "Etternavn": "Ghotbi",
    "Kjonn": "Mann",
    "Alder": 47,
    "ArbStedNr": "1306000201",
    "Arbeidsted": "Driftsområde - 1 Voss",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "751701",
    "Stillingsbeskrivelse": "Driftsopperatør m/fagbrev",
    "ArsLonn": 358800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4786,
    "Fornavn": "Ingse",
    "Etternavn": "Sommerlade",
    "Kjonn": "Kvinne",
    "Alder": 34,
    "ArbStedNr": "63860000",
    "Arbeidsted": "Åsane vgs - Avd. AF",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "796611",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd. i",
    "ArsLonn": 473100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4789,
    "Fornavn": "Dahir",
    "Etternavn": "Arumaiturai",
    "Kjonn": "Mann",
    "Alder": 53,
    "ArbStedNr": "63070000",
    "Arbeidsted": "Kvinnherad vgs - Avd. Valekrossen",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "657201",
    "Stillingsbeskrivelse": "Miljøassistent",
    "ArsLonn": 338300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 9.50,
    "KravTilbut": "False"
  },
  {
    "Id": 4791,
    "Fornavn": "Arturo",
    "Etternavn": "Dalanger",
    "Kjonn": "Mann",
    "Alder": 55,
    "ArbStedNr": "65550000",
    "Arbeidsted": "Bergen Maritime Fagskole - Avd. Maritim",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4797,
    "Fornavn": "Shaiban",
    "Etternavn": "Høvik",
    "Kjonn": "Mann",
    "Alder": 67,
    "ArbStedNr": "64610000",
    "Arbeidsted": "OS VGS",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "995100",
    "Stillingsbeskrivelse": "Rektor                        ",
    "ArsLonn": 673000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4802,
    "Fornavn": "Imran",
    "Etternavn": "Romm",
    "Kjonn": "Mann",
    "Alder": 42,
    "ArbStedNr": "65560000",
    "Arbeidsted": "Bergen Maritime vgs - Avd. Elektro og Mekanisk",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796100",
    "Stillingsbeskrivelse": "Lærer",
    "ArsLonn": 435200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4810,
    "Fornavn": "Nicanor",
    "Etternavn": "Rangsæter",
    "Kjonn": "Mann",
    "Alder": 19,
    "ArbStedNr": "1306000210",
    "Arbeidsted": "Driftsområde - 10 Fana",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønn",
    "Stillingskode": "657200",
    "Stillingsbeskrivelse": "Assistent",
    "ArsLonn": 262100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4814,
    "Fornavn": "Vivian",
    "Etternavn": "Ulbrandt",
    "Kjonn": "Kvinne",
    "Alder": 28,
    "ArbStedNr": "16040000",
    "Arbeidsted": "Planseksjonen - REG.AVD.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "853000",
    "Stillingsbeskrivelse": "Rådgjevar",
    "ArsLonn": 435000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4824,
    "Fornavn": "Gislaug",
    "Etternavn": "Baggerød",
    "Kjonn": "Kvinne",
    "Alder": 38,
    "ArbStedNr": "40040000",
    "Arbeidsted": "Fylkesbiblioteket - Kultur- og idrettsavd.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "853001",
    "Stillingsbeskrivelse": "Spesialrådgjevar          ",
    "ArsLonn": 415000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 60.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4829,
    "Fornavn": "Netta",
    "Etternavn": "Rustenberg",
    "Kjonn": "Kvinne",
    "Alder": 39,
    "ArbStedNr": "66570000",
    "Arbeidsted": "Stord vgs - Avd. Stud.spes/Språk/Samf/Økonom.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796611",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd. i",
    "ArsLonn": 494500.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 80.80,
    "KravTilbut": "False"
  },
  {
    "Id": 4830,
    "Fornavn": "Enilda",
    "Etternavn": "Dalgrav",
    "Kjonn": "Kvinne",
    "Alder": 27,
    "ArbStedNr": "5007000100",
    "Arbeidsted": "THD. Aust, Odda",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "830100",
    "Stillingsbeskrivelse": "Tannlege",
    "ArsLonn": 521000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4834,
    "Fornavn": "Onisoa",
    "Etternavn": "Ghotbi",
    "Kjonn": "Kvinne",
    "Alder": 59,
    "ArbStedNr": "61740000",
    "Arbeidsted": "Tertnes vgs - Stab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "721000",
    "Stillingsbeskrivelse": "Renholder",
    "ArsLonn": 338300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 68.50,
    "KravTilbut": "False"
  },
  {
    "Id": 4838,
    "Fornavn": "Yvonne",
    "Etternavn": "Sonthiporn",
    "Kjonn": "Kvinne",
    "Alder": 45,
    "ArbStedNr": "62850000",
    "Arbeidsted": "Odda vgs - Avd. Yrkesfag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796311",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning i",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4840,
    "Fornavn": "Nicolas",
    "Etternavn": "Barhoon",
    "Kjonn": "Mann",
    "Alder": 49,
    "ArbStedNr": "63870000",
    "Arbeidsted": "Åsane vgs - Avd. HI",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4841,
    "Fornavn": "Sigvald",
    "Etternavn": "Skogdalen",
    "Kjonn": "Mann",
    "Alder": 53,
    "ArbStedNr": "13040000",
    "Arbeidsted": "Fylkeskassen - Økonomiavd.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "853001",
    "Stillingsbeskrivelse": "Spesialrådgjevar          ",
    "ArsLonn": 418000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4843,
    "Fornavn": "Yoseph",
    "Etternavn": "Ditlevsen",
    "Kjonn": "Mann",
    "Alder": 53,
    "ArbStedNr": "3006000500",
    "Arbeidsted": "Drift - Skyss",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "853000",
    "Stillingsbeskrivelse": "Rådgjevar",
    "ArsLonn": 492000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4845,
    "Fornavn": "Janus",
    "Etternavn": "Cai",
    "Kjonn": "Mann",
    "Alder": 31,
    "ArbStedNr": "3006000100",
    "Arbeidsted": "Kundesenter - Skyss",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "691200",
    "Stillingsbeskrivelse": "Servicemedarbeider",
    "ArsLonn": 298200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4849,
    "Fornavn": "Qasim",
    "Etternavn": "Ene",
    "Kjonn": "Mann",
    "Alder": 60,
    "ArbStedNr": "65730000",
    "Arbeidsted": "Hjeltnes vgs - Avd. Vidaregåande oppl.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463900.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4853,
    "Fornavn": "Yassin",
    "Etternavn": "Manneråk",
    "Kjonn": "Kvinne",
    "Alder": 58,
    "ArbStedNr": "64120000",
    "Arbeidsted": "Austrheim vgs - Adm.stab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "721000",
    "Stillingsbeskrivelse": "Renholder",
    "ArsLonn": 338300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 59.20,
    "KravTilbut": "False"
  },
  {
    "Id": 4856,
    "Fornavn": "Eirik",
    "Etternavn": "Almassy",
    "Kjonn": "Mann",
    "Alder": 65,
    "ArbStedNr": "66591000",
    "Arbeidsted": "Stord vgs - Avd. Opplæringssenteret",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4858,
    "Fornavn": "Raziye",
    "Etternavn": "Abild",
    "Kjonn": "Kvinne",
    "Alder": 55,
    "ArbStedNr": "5005000100",
    "Arbeidsted": "THD. Vest, Loddefjord",
    "ArbfNr": 2,
    "Ansattforhold": "Fast",
    "Stillingskode": "710000",
    "Stillingsbeskrivelse": "Tannhelsesekretær",
    "ArsLonn": 358800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 44.50,
    "KravTilbut": "False"
  },
  {
    "Id": 4864,
    "Fornavn": "Cvijeta",
    "Etternavn": "Nenseter",
    "Kjonn": "Kvinne",
    "Alder": 55,
    "ArbStedNr": "5003000106",
    "Arbeidsted": "THD. Sentrum, Tannlegevakt",
    "ArbfNr": 2,
    "Ansattforhold": "Fast ansatt (TURNUS)",
    "Stillingskode": "710001",
    "Stillingsbeskrivelse": "Tannhelsesekretær i      ",
    "ArsLonn": 359000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 14.80,
    "KravTilbut": "False"
  },
  {
    "Id": 4868,
    "Fornavn": "Cvijeta",
    "Etternavn": "Nenseter",
    "Kjonn": "Kvinne",
    "Alder": 55,
    "ArbStedNr": "5004000103",
    "Arbeidsted": "THD. Nord, Bergen Fengsel",
    "ArbfNr": 1,
    "Ansattforhold": "Fast ansatt (TURNUS)",
    "Stillingskode": "710001",
    "Stillingsbeskrivelse": "Tannhelsesekretær i      ",
    "ArsLonn": 359000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 85.20,
    "KravTilbut": "False"
  },
  {
    "Id": 4870,
    "Fornavn": "Øzlem",
    "Etternavn": "Størset",
    "Kjonn": "Kvinne",
    "Alder": 29,
    "ArbStedNr": "65880000",
    "Arbeidsted": "DIVERSE - Stend vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796500",
    "Stillingsbeskrivelse": "Lektor",
    "ArsLonn": 414700.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4872,
    "Fornavn": "Andre",
    "Etternavn": "Soberano",
    "Kjonn": "Mann",
    "Alder": 57,
    "ArbStedNr": "63950000",
    "Arbeidsted": "Årstad vgs - Avd. Formgiving",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 555100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4875,
    "Fornavn": "Hanne",
    "Etternavn": "Mobakken",
    "Kjonn": "Kvinne",
    "Alder": 54,
    "ArbStedNr": "63850000",
    "Arbeidsted": "Åsane vgs - Avd. SP/HS",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 555100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 60.12,
    "KravTilbut": "False"
  },
  {
    "Id": 4877,
    "Fornavn": "Cille",
    "Etternavn": "Dåbu",
    "Kjonn": "Kvinne",
    "Alder": 62,
    "ArbStedNr": "62670000",
    "Arbeidsted": "Sandsli vgs - Avd. Språk/Samf.fag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796611",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd. i",
    "ArsLonn": 555100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4880,
    "Fornavn": "Renata",
    "Etternavn": "Vahedi",
    "Kjonn": "Kvinne",
    "Alder": 37,
    "ArbStedNr": "61540000",
    "Arbeidsted": "Øystese gymnas - Avd. Vg1 og innfør.klasse",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 448400.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 41.52,
    "KravTilbut": "False"
  },
  {
    "Id": 4883,
    "Fornavn": "Ketil",
    "Etternavn": "Liøkel",
    "Kjonn": "Mann",
    "Alder": 28,
    "ArbStedNr": "64350000",
    "Arbeidsted": "Askøy vgs - Studiesp. 2",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 395900.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 75.09,
    "KravTilbut": "False"
  },
  {
    "Id": 4888,
    "Fornavn": "Gholam",
    "Etternavn": "Wanderås",
    "Kjonn": "Mann",
    "Alder": 64,
    "ArbStedNr": "63960000",
    "Arbeidsted": "Årstad vgs -  Avd. Tilrettelagt",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "995102",
    "Stillingsbeskrivelse": "Avdelingsleiar           ",
    "ArsLonn": 578000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4907,
    "Fornavn": "Elena",
    "Etternavn": "Sandsdalen",
    "Kjonn": "Kvinne",
    "Alder": 29,
    "ArbStedNr": "5004000104",
    "Arbeidsted": "THD. Nord, Lindås",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "830100",
    "Stillingsbeskrivelse": "Tannlege",
    "ArsLonn": 508000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 60.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4910,
    "Fornavn": "Hadish",
    "Etternavn": "Waage",
    "Kjonn": "Mann",
    "Alder": 43,
    "ArbStedNr": "30030000",
    "Arbeidsted": "Forvaltningseksjonen - SAMF.AVD.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "853002",
    "Stillingsbeskrivelse": "Seniorrådgjevar          ",
    "ArsLonn": 449000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4912,
    "Fornavn": "Gislaug",
    "Etternavn": "Sundar",
    "Kjonn": "Kvinne",
    "Alder": 46,
    "ArbStedNr": "64460000",
    "Arbeidsted": "Fusa vgs - Avd. FF/NA/FO/TP",
    "ArbfNr": 2,
    "Ansattforhold": "Fast",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 448400.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 42.98,
    "KravTilbut": "False"
  },
  {
    "Id": 4915,
    "Fornavn": "Annett",
    "Etternavn": "Sangro",
    "Kjonn": "Kvinne",
    "Alder": 37,
    "ArbStedNr": "66130000",
    "Arbeidsted": "Olsvikåsen vgs - Avd. tilrettelagt opplæring",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "657201",
    "Stillingsbeskrivelse": "Miljøassistent",
    "ArsLonn": 328300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 89.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4918,
    "Fornavn": "Torje",
    "Etternavn": "Stapnes",
    "Kjonn": "Mann",
    "Alder": 55,
    "ArbStedNr": "63540000",
    "Arbeidsted": "Norheimsund vgs - Avd. DH/EL/HS",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4923,
    "Fornavn": "Siamek",
    "Etternavn": "Tvetene",
    "Kjonn": "Mann",
    "Alder": 46,
    "ArbStedNr": "63980000",
    "Arbeidsted": "Årstad vgs - Avd. Byggfag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "795402",
    "Stillingsbeskrivelse": "Programfagleder",
    "ArsLonn": 569400.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4927,
    "Fornavn": "Adeel",
    "Etternavn": "Dalgrav",
    "Kjonn": "Mann",
    "Alder": 58,
    "ArbStedNr": "64460000",
    "Arbeidsted": "Fusa vgs - Avd. FF/NA/FO/TP",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796311",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning i",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 80.10,
    "KravTilbut": "False"
  },
  {
    "Id": 4929,
    "Fornavn": "Bjarte",
    "Etternavn": "Amdal",
    "Kjonn": "Mann",
    "Alder": 42,
    "ArbStedNr": "65940000",
    "Arbeidsted": "Voss jbs - Avd. Skule ped.pers.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 451400.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4933,
    "Fornavn": "Saleban",
    "Etternavn": "Leland",
    "Kjonn": "Mann",
    "Alder": 54,
    "ArbStedNr": "1306000214",
    "Arbeidsted": "Driftsområde - 14 Stord ",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "700311",
    "Stillingsbeskrivelse": "Ass. driftsleder m/fagb. ",
    "ArsLonn": 364000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4935,
    "Fornavn": "Torunn",
    "Etternavn": "Kvidal",
    "Kjonn": "Kvinne",
    "Alder": 45,
    "ArbStedNr": "63220000",
    "Arbeidsted": "Voss vgs - Adm.stab",
    "ArbfNr": 2,
    "Ansattforhold": "Fast",
    "Stillingskode": "655900",
    "Stillingsbeskrivelse": "Konsulent",
    "ArsLonn": 364000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 60.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4938,
    "Fornavn": "Kunal",
    "Etternavn": "Myran",
    "Kjonn": "Mann",
    "Alder": 27,
    "ArbStedNr": "61860000",
    "Arbeidsted": "DIVERSE - Tanks vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "796100",
    "Stillingsbeskrivelse": "Lærer",
    "ArsLonn": 355100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 8.83,
    "KravTilbut": "False"
  },
  {
    "Id": 4946,
    "Fornavn": "Kubra",
    "Etternavn": "Øyerhamn",
    "Kjonn": "Kvinne",
    "Alder": 40,
    "ArbStedNr": "40060000",
    "Arbeidsted": "Kulturminnevern og museum - Kultur- og idrettsavd.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "853001",
    "Stillingsbeskrivelse": "Spesialrådgjevar          ",
    "ArsLonn": 457000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4950,
    "Fornavn": "Ørjan",
    "Etternavn": "Ådnøy",
    "Kjonn": "Mann",
    "Alder": 47,
    "ArbStedNr": "63560000",
    "Arbeidsted": "Norheimsund vgs - Avd. BA/TIP",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4952,
    "Fornavn": "Torild",
    "Etternavn": "Lebrun",
    "Kjonn": "Kvinne",
    "Alder": 57,
    "ArbStedNr": "13060000",
    "Arbeidsted": "Eigedomsseksjonen - Økonomiavd.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "655900",
    "Stillingsbeskrivelse": "Konsulent",
    "ArsLonn": 366000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 80.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4953,
    "Fornavn": "Hanno",
    "Etternavn": "Dørum",
    "Kjonn": "Mann",
    "Alder": 55,
    "ArbStedNr": "65540000",
    "Arbeidsted": "Bergen Maritime vgs - Avd. Maritim utd.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4955,
    "Fornavn": "Tabark",
    "Etternavn": "Kutzbach",
    "Kjonn": "Kvinne",
    "Alder": 50,
    "ArbStedNr": "65610000",
    "Arbeidsted": "LØNBORG VGS",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "995100",
    "Stillingsbeskrivelse": "Rektor                        ",
    "ArsLonn": 648000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4959,
    "Fornavn": "Elin",
    "Etternavn": "Kvia",
    "Kjonn": "Kvinne",
    "Alder": 28,
    "ArbStedNr": "65260000",
    "Arbeidsted": "DIVERSE - Fitjar vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796000",
    "Stillingsbeskrivelse": "Lærer u/godkj.utdannelse",
    "ArsLonn": 307000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4963,
    "Fornavn": "Frewini",
    "Etternavn": "Milch",
    "Kjonn": "Kvinne",
    "Alder": 59,
    "ArbStedNr": "64520000",
    "Arbeidsted": "Sotra vgs - Driftsstab",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønn",
    "Stillingskode": "721000",
    "Stillingsbeskrivelse": "Renholder",
    "ArsLonn": 338300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4967,
    "Fornavn": "Jasmin",
    "Etternavn": "Myrset",
    "Kjonn": "Mann",
    "Alder": 53,
    "ArbStedNr": "3203000300",
    "Arbeidsted": "Utbygging (Grunn/Tunnel) - Bybanen utbygging",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "845102",
    "Stillingsbeskrivelse": "Byggeleiar",
    "ArsLonn": 555000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4970,
    "Fornavn": "Minda",
    "Etternavn": "Snaunes",
    "Kjonn": "Kvinne",
    "Alder": 44,
    "ArbStedNr": "66340000",
    "Arbeidsted": "Nordahl Grieg vgs - Avd. Stud.spes 2",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796311",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning i",
    "ArsLonn": 451400.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4974,
    "Fornavn": "Louise",
    "Etternavn": "Albrektsen",
    "Kjonn": "Kvinne",
    "Alder": 25,
    "ArbStedNr": "3006000100",
    "Arbeidsted": "Kundesenter - Skyss",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "691200",
    "Stillingsbeskrivelse": "Servicemedarbeider",
    "ArsLonn": 300200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4976,
    "Fornavn": "Nasrin",
    "Etternavn": "Bråtveit",
    "Kjonn": "Kvinne",
    "Alder": 54,
    "ArbStedNr": "1404000200",
    "Arbeidsted": "Info- og servicesenter - Personalseksjonen",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "655901",
    "Stillingsbeskrivelse": "Førstekonsulent          ",
    "ArsLonn": 377000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4979,
    "Fornavn": "Sylvia",
    "Etternavn": "Blendberg",
    "Kjonn": "Kvinne",
    "Alder": 28,
    "ArbStedNr": "62060000",
    "Arbeidsted": "Langhaugen vgs - Avd. Språk/Samf.",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 448400.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 78.97,
    "KravTilbut": "False"
  },
  {
    "Id": 4983,
    "Fornavn": "Grorud",
    "Etternavn": "Kiedzierska",
    "Kjonn": "Kvinne",
    "Alder": 45,
    "ArbStedNr": "63560000",
    "Arbeidsted": "Norheimsund vgs - Avd. BA/TIP",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 19.38,
    "KravTilbut": "False"
  },
  {
    "Id": 4987,
    "Fornavn": "Johnny",
    "Etternavn": "Falsen",
    "Kjonn": "Mann",
    "Alder": 40,
    "ArbStedNr": "6388000100",
    "Arbeidsted": "Åsane vgs - Avd. BF",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 451400.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 17.71,
    "KravTilbut": "False"
  },
  {
    "Id": 4990,
    "Fornavn": "Betel",
    "Etternavn": "Line",
    "Kjonn": "Kvinne",
    "Alder": 44,
    "ArbStedNr": "3006000200",
    "Arbeidsted": "Administrasjon - Skyss",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "853011",
    "Stillingsbeskrivelse": "Controller               ",
    "ArsLonn": 537000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4993,
    "Fornavn": "Dagfinn",
    "Etternavn": "Lehre",
    "Kjonn": "Mann",
    "Alder": 30,
    "ArbStedNr": "64520000",
    "Arbeidsted": "Sotra vgs - Driftsstab",
    "ArbfNr": 1,
    "Ansattforhold": "Engasjement",
    "Stillingskode": "888800",
    "Stillingsbeskrivelse": "Ekstra sysselsatte",
    "ArsLonn": 1.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4995,
    "Fornavn": "Ineke",
    "Etternavn": "Brose",
    "Kjonn": "Kvinne",
    "Alder": 66,
    "ArbStedNr": "62120000",
    "Arbeidsted": "Bergen Katedralskole - Fagstab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "721000",
    "Stillingsbeskrivelse": "Renholder",
    "ArsLonn": 358800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 4999,
    "Fornavn": "Harold",
    "Etternavn": "Bergman",
    "Kjonn": "Mann",
    "Alder": 26,
    "ArbStedNr": "62150000",
    "Arbeidsted": "Bergen Katedralskole - Pedagogisk stab",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796100",
    "Stillingsbeskrivelse": "Lærer",
    "ArsLonn": 355100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5002,
    "Fornavn": "Halvard",
    "Etternavn": "Secka",
    "Kjonn": "Mann",
    "Alder": 52,
    "ArbStedNr": "1306000201",
    "Arbeidsted": "Driftsområde - 1 Voss",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "700399",
    "Stillingsbeskrivelse": "Teknisk leder områdekoord",
    "ArsLonn": 369000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5007,
    "Fornavn": "Tuyoba",
    "Etternavn": "Åkset",
    "Kjonn": "Kvinne",
    "Alder": 42,
    "ArbStedNr": "5003000108",
    "Arbeidsted": "THD. Sentrum, Sørås",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "710000",
    "Stillingsbeskrivelse": "Tannhelsesekretær",
    "ArsLonn": 358800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 50.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5010,
    "Fornavn": "Chiawei",
    "Etternavn": "Meidel",
    "Kjonn": "Kvinne",
    "Alder": 44,
    "ArbStedNr": "63950000",
    "Arbeidsted": "Årstad vgs - Avd. Formgiving",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796611",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd. i",
    "ArsLonn": 494500.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5012,
    "Fornavn": "Kinjal",
    "Etternavn": "Barbero",
    "Kjonn": "Kvinne",
    "Alder": 52,
    "ArbStedNr": "64210000",
    "Arbeidsted": "BERGEN TEKNISKE FAGSKOLE",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "795400",
    "Stillingsbeskrivelse": "Avd.led/u.insp/fagleder",
    "ArsLonn": 574700.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5014,
    "Fornavn": "Darren",
    "Etternavn": "Moghus",
    "Kjonn": "Mann",
    "Alder": 51,
    "ArbStedNr": "63050000",
    "Arbeidsted": "Kvinnherad vgs - Avd. Studspes/Fellesfag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 473100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5015,
    "Fornavn": "Synne",
    "Etternavn": "Hasanagic",
    "Kjonn": "Kvinne",
    "Alder": 39,
    "ArbStedNr": "66320001",
    "Arbeidsted": "Nordahl Grieg vgs - Adm.stab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "655900",
    "Stillingsbeskrivelse": "Konsulent",
    "ArsLonn": 393500.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5020,
    "Fornavn": "Filipe",
    "Etternavn": "Mengistu",
    "Kjonn": "Mann",
    "Alder": 28,
    "ArbStedNr": "65640000",
    "Arbeidsted": "DIVERSE - Lønborg vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønn",
    "Stillingskode": "657200",
    "Stillingsbeskrivelse": "Assistent",
    "ArsLonn": 262100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5023,
    "Fornavn": "Melvin",
    "Etternavn": "Aamann",
    "Kjonn": "Mann",
    "Alder": 20,
    "ArbStedNr": "65950000",
    "Arbeidsted": "DIVERSE - Voss jbs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønn",
    "Stillingskode": "601400",
    "Stillingsbeskrivelse": "Arbeider",
    "ArsLonn": 298200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5026,
    "Fornavn": "Edvin",
    "Etternavn": "Mobacken",
    "Kjonn": "Mann",
    "Alder": 67,
    "ArbStedNr": "64670000",
    "Arbeidsted": "Os vgs - Avd. Transport/yrkessjåfør",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5028,
    "Fornavn": "Øyunn",
    "Etternavn": "Hanche",
    "Kjonn": "Kvinne",
    "Alder": 47,
    "ArbStedNr": "64260000",
    "Arbeidsted": "Bergen Tekn. Fag. - Avd. Elektro og prosess",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5030,
    "Fornavn": "Gertrud",
    "Etternavn": "Saravanapavan",
    "Kjonn": "Kvinne",
    "Alder": 56,
    "ArbStedNr": "63380000",
    "Arbeidsted": "DIVERSE - Slåtthaug vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796100",
    "Stillingsbeskrivelse": "Lærer",
    "ArsLonn": 435200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5034,
    "Fornavn": "Hajar",
    "Etternavn": "Nie",
    "Kjonn": "Mann",
    "Alder": 30,
    "ArbStedNr": "63690000",
    "Arbeidsted": "Laksevåg vgs - Byggfag",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "657201",
    "Stillingsbeskrivelse": "Miljøassistent",
    "ArsLonn": 328300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 89.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5036,
    "Fornavn": "Oddgeir",
    "Etternavn": "Mehling",
    "Kjonn": "Mann",
    "Alder": 31,
    "ArbStedNr": "61740000",
    "Arbeidsted": "Tertnes vgs - Stab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "655921",
    "Stillingsbeskrivelse": "Ikt-konsulent i",
    "ArsLonn": 390000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5040,
    "Fornavn": "Heidrun",
    "Etternavn": "Randsborg",
    "Kjonn": "Kvinne",
    "Alder": 69,
    "ArbStedNr": "66380000",
    "Arbeidsted": "Nordahl Grieg vgs - Avd. Yrkesfag 1",
    "ArbfNr": 4,
    "Ansattforhold": "Pensjonist",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Timelønnet lærer - pensjonist",
    "ArsLonn": 482700.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5043,
    "Fornavn": "Malik",
    "Etternavn": "Kjenseth",
    "Kjonn": "Mann",
    "Alder": 40,
    "ArbStedNr": "3203000100",
    "Arbeidsted": "Utbygging (Elektro) Bybanen utbygging",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "945120",
    "Stillingsbeskrivelse": "Prosjektleiar",
    "ArsLonn": 810000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5045,
    "Fornavn": "Bjørn Tore",
    "Etternavn": "Henriksen",
    "Kjonn": "Mann",
    "Alder": 44,
    "ArbStedNr": "62550000",
    "Arbeidsted": "DIVERSE - Osterøy vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5047,
    "Fornavn": "Aamodt",
    "Etternavn": "Vanhanen",
    "Kjonn": "Kvinne",
    "Alder": 38,
    "ArbStedNr": "65040000",
    "Arbeidsted": "Voss hfs - Avd. Ped.personale",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 494500.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5050,
    "Fornavn": "Arnliss",
    "Etternavn": "Pripp",
    "Kjonn": "Kvinne",
    "Alder": 56,
    "ArbStedNr": "63340000",
    "Arbeidsted": "Slåtthaug vgs - Avd. BY/EL /TIP",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5053,
    "Fornavn": "Grethe-Elin",
    "Etternavn": "Lohne",
    "Kjonn": "Kvinne",
    "Alder": 50,
    "ArbStedNr": "65850000",
    "Arbeidsted": "Stend vgs - Avd. Tilrettelagt",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "751706",
    "Stillingsbeskrivelse": "MILJØFAGARBEIDER (FAGBR.)",
    "ArsLonn": 358800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 44.50,
    "KravTilbut": "False"
  },
  {
    "Id": 5055,
    "Fornavn": "Kjerst",
    "Etternavn": "Höök",
    "Kjonn": "Kvinne",
    "Alder": 55,
    "ArbStedNr": "62660000",
    "Arbeidsted": "Sandsli vgs - Avd. Realfag/Økon.fag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796311",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning i",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5058,
    "Fornavn": "Abeba",
    "Etternavn": "Øyerhamn",
    "Kjonn": "Kvinne",
    "Alder": 33,
    "ArbStedNr": "62080000",
    "Arbeidsted": "DIVERSE - Langhaugen vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 395900.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5061,
    "Fornavn": "Bridget",
    "Etternavn": "Jordens",
    "Kjonn": "Kvinne",
    "Alder": 49,
    "ArbStedNr": "65850000",
    "Arbeidsted": "Stend vgs - Avd. Tilrettelagt",
    "ArbfNr": 2,
    "Ansattforhold": "Fast",
    "Stillingskode": "657202",
    "Stillingsbeskrivelse": "Miljøassistent (sfo)     ",
    "ArsLonn": 328300.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 22.55,
    "KravTilbut": "False"
  },
  {
    "Id": 5062,
    "Fornavn": "Faith",
    "Etternavn": "Ghotbi",
    "Kjonn": "Kvinne",
    "Alder": 58,
    "ArbStedNr": "5005000103",
    "Arbeidsted": "THD. Vest, Kleppestø",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "710000",
    "Stillingsbeskrivelse": "Tannhelsesekretær",
    "ArsLonn": 358800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5064,
    "Fornavn": "Milena",
    "Etternavn": "Asmaro",
    "Kjonn": "Kvinne",
    "Alder": 64,
    "ArbStedNr": "64540000",
    "Arbeidsted": "Sotra vgs - DH/FO/ID",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796311",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning i",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5067,
    "Fornavn": "Lucille",
    "Etternavn": "Tvedby",
    "Kjonn": "Kvinne",
    "Alder": 57,
    "ArbStedNr": "65710000",
    "Arbeidsted": "HJELTNES VGS",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "995100",
    "Stillingsbeskrivelse": "Rektor                        ",
    "ArsLonn": 647000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5069,
    "Fornavn": "Helle",
    "Etternavn": "Vovk",
    "Kjonn": "Kvinne",
    "Alder": 53,
    "ArbStedNr": "63860000",
    "Arbeidsted": "Åsane vgs - Avd. AF",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5071,
    "Fornavn": "Antone",
    "Etternavn": "Hildebrandt",
    "Kjonn": "Kvinne",
    "Alder": 60,
    "ArbStedNr": "64570000",
    "Arbeidsted": "Sotra vgs - BA/HS",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 558500.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5074,
    "Fornavn": "Mitra",
    "Etternavn": "Streuli",
    "Kjonn": "Kvinne",
    "Alder": 57,
    "ArbStedNr": "63060000",
    "Arbeidsted": "Kvinnherad vgs - Avd. Yrkesfag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5076,
    "Fornavn": "Olgar",
    "Etternavn": "Ebrahimi",
    "Kjonn": "Mann",
    "Alder": 42,
    "ArbStedNr": "64240000",
    "Arbeidsted": "Bergen Tekn. Fag. - Avd. STO/FIH/Mester",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 14.06,
    "KravTilbut": "False"
  },
  {
    "Id": 5079,
    "Fornavn": "Evija",
    "Etternavn": "Nærbø",
    "Kjonn": "Kvinne",
    "Alder": 49,
    "ArbStedNr": "40030000",
    "Arbeidsted": "Fylkesarkivet - Kultur- og idrettsavd.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "945100",
    "Stillingsbeskrivelse": "Leiar",
    "ArsLonn": 580000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5083,
    "Fornavn": "Rocco",
    "Etternavn": "Almendingen",
    "Kjonn": "Mann",
    "Alder": 28,
    "ArbStedNr": "61270000",
    "Arbeidsted": "DIVERSE - Fana gymnas",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 413900.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5086,
    "Fornavn": "Johnas",
    "Etternavn": "Spjøtvold",
    "Kjonn": "Mann",
    "Alder": 49,
    "ArbStedNr": "61730000",
    "Arbeidsted": "Tertnes vgs - Avd. DH/S&S/Formgjev.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796611",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd. i",
    "ArsLonn": 473100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5088,
    "Fornavn": "Tiril",
    "Etternavn": "Agnholm",
    "Kjonn": "Kvinne",
    "Alder": 45,
    "ArbStedNr": "63050000",
    "Arbeidsted": "Kvinnherad vgs - Avd. Studspes/Fellesfag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5090,
    "Fornavn": "Alexander Holvik",
    "Etternavn": "Nygård",
    "Kjonn": "Mann",
    "Alder": 20,
    "ArbStedNr": "66390000",
    "Arbeidsted": "DIVERSE - Nordahl Grieg vgs",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønn",
    "Stillingskode": "657201",
    "Stillingsbeskrivelse": "Miljøassistent",
    "ArsLonn": 262100.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5093,
    "Fornavn": "Péter",
    "Etternavn": "Line",
    "Kjonn": "Mann",
    "Alder": 63,
    "ArbStedNr": "63050000",
    "Arbeidsted": "Kvinnherad vgs - Avd. Studspes/Fellesfag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796311",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning i",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 60.70,
    "KravTilbut": "False"
  },
  {
    "Id": 5095,
    "Fornavn": "Tewolde",
    "Etternavn": "Bjerring",
    "Kjonn": "Mann",
    "Alder": 42,
    "ArbStedNr": "65550000",
    "Arbeidsted": "Bergen Maritime Fagskole - Avd. Maritim",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "796200",
    "Stillingsbeskrivelse": "Adjunkt",
    "ArsLonn": 463200.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5099,
    "Fornavn": "Jannie",
    "Etternavn": "Thilen",
    "Kjonn": "Kvinne",
    "Alder": 55,
    "ArbStedNr": "63480000",
    "Arbeidsted": "Knarvik vgs - Avd. VO",
    "ArbfNr": 1,
    "Ansattforhold": "Timelønnet Lærer",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 451400.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 0.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5101,
    "Fornavn": "Femia",
    "Etternavn": "Darre",
    "Kjonn": "Kvinne",
    "Alder": 47,
    "ArbStedNr": "5003000117",
    "Arbeidsted": "THD. Sentrum, Årstad",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "830100",
    "Stillingsbeskrivelse": "Tannlege",
    "ArsLonn": 574000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 60.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5104,
    "Fornavn": "Juhana",
    "Etternavn": "Gussiås",
    "Kjonn": "Kvinne",
    "Alder": 49,
    "ArbStedNr": "65650000",
    "Arbeidsted": "Lønborg vgs - Avd. Helse og sosial",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 464700.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 50.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5108,
    "Fornavn": "Oddrun",
    "Etternavn": "Mihaila",
    "Kjonn": "Kvinne",
    "Alder": 45,
    "ArbStedNr": "66120000",
    "Arbeidsted": "Olsvikåsen vgs - Adm.stab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "752000",
    "Stillingsbeskrivelse": "Førstesekretær",
    "ArsLonn": 359000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 65.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5109,
    "Fornavn": "Svend",
    "Etternavn": "Kvidal",
    "Kjonn": "Mann",
    "Alder": 38,
    "ArbStedNr": "64460000",
    "Arbeidsted": "Fusa vgs - Avd. FF/NA/FO/TP",
    "ArbfNr": 1,
    "Ansattforhold": "Vikar",
    "Stillingskode": "796600",
    "Stillingsbeskrivelse": "Lektor m/tilleggsutd.",
    "ArsLonn": 459700.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5110,
    "Fornavn": "Khiem",
    "Etternavn": "Rydenbàck",
    "Kjonn": "Mann",
    "Alder": 39,
    "ArbStedNr": "63760000",
    "Arbeidsted": "Arna vgs - Avd. TIP/HS",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796100",
    "Stillingsbeskrivelse": "Lærer",
    "ArsLonn": 391000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5113,
    "Fornavn": "Anika",
    "Etternavn": "Drivenes",
    "Kjonn": "Kvinne",
    "Alder": 51,
    "ArbStedNr": "61850000",
    "Arbeidsted": "Tanks vgs - Avd. språk og samfunnsfag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796311",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning i",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 77.38,
    "KravTilbut": "False"
  },
  {
    "Id": 5117,
    "Fornavn": "Annie",
    "Etternavn": "Stenberg",
    "Kjonn": "Kvinne",
    "Alder": 43,
    "ArbStedNr": "5003000102",
    "Arbeidsted": "THD. Sentrum, Odontofobi",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "847000",
    "Stillingsbeskrivelse": "Psykolog",
    "ArsLonn": 500000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 50.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5121,
    "Fornavn": "Elisabeth",
    "Etternavn": "Helle",
    "Kjonn": "Kvinne",
    "Alder": 34,
    "ArbStedNr": "5004000101",
    "Arbeidsted": "THD. Nord, Rolland",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "717500",
    "Stillingsbeskrivelse": "Tannpleier",
    "ArsLonn": 357900.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 50.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5123,
    "Fornavn": "Fawzieh",
    "Etternavn": "Kutra",
    "Kjonn": "Kvinne",
    "Alder": 38,
    "ArbStedNr": "5004000102",
    "Arbeidsted": "THD. Nord, Indre Arna",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "710000",
    "Stillingsbeskrivelse": "Tannhelsesekretær",
    "ArsLonn": 358800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5125,
    "Fornavn": "Maeyia",
    "Etternavn": "Grimsland",
    "Kjonn": "Kvinne",
    "Alder": 52,
    "ArbStedNr": "5005000100",
    "Arbeidsted": "THD. Vest, Loddefjord",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "717501",
    "Stillingsbeskrivelse": "Tannpleier i             ",
    "ArsLonn": 402000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5127,
    "Fornavn": "Lemlem",
    "Etternavn": "Komada",
    "Kjonn": "Kvinne",
    "Alder": 50,
    "ArbStedNr": "5003000108",
    "Arbeidsted": "THD. Sentrum, Sørås",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "710000",
    "Stillingsbeskrivelse": "Tannhelsesekretær",
    "ArsLonn": 358800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5131,
    "Fornavn": "Nadia",
    "Etternavn": "Rye",
    "Kjonn": "Kvinne",
    "Alder": 28,
    "ArbStedNr": "66320001",
    "Arbeidsted": "Nordahl Grieg vgs - Adm.stab",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "655900",
    "Stillingsbeskrivelse": "Konsulent",
    "ArsLonn": 344000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 20.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5135,
    "Fornavn": "Illrid",
    "Etternavn": "Arstein",
    "Kjonn": "Kvinne",
    "Alder": 49,
    "ArbStedNr": "65920000",
    "Arbeidsted": "Voss jbs - Stab (Skule støttepers.)",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "667500",
    "Stillingsbeskrivelse": "Miljøterapeut",
    "ArsLonn": 393000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5137,
    "Fornavn": "Bjørnar",
    "Etternavn": "Etnestad",
    "Kjonn": "Mann",
    "Alder": 65,
    "ArbStedNr": "63050000",
    "Arbeidsted": "Kvinnherad vgs - Avd. Studspes/Fellesfag",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796311",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning i",
    "ArsLonn": 528700.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 81.44,
    "KravTilbut": "False"
  },
  {
    "Id": 5139,
    "Fornavn": "Lillann",
    "Etternavn": "Tybakken",
    "Kjonn": "Kvinne",
    "Alder": 62,
    "ArbStedNr": "63440000",
    "Arbeidsted": "Knarvik vgs - Avd. BA/DH/HS",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "796300",
    "Stillingsbeskrivelse": "Adjunkt m. tilleggsutdanning",
    "ArsLonn": 493800.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5142,
    "Fornavn": "Stein",
    "Etternavn": "Hertel",
    "Kjonn": "Mann",
    "Alder": 56,
    "ArbStedNr": "40060000",
    "Arbeidsted": "Kulturminnevern og museum - Kultur- og idrettsavd.",
    "ArbfNr": 1,
    "Ansattforhold": "Fast",
    "Stillingskode": "845100",
    "Stillingsbeskrivelse": "Leiar",
    "ArsLonn": 503000.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 100.0,
    "KravTilbut": "False"
  },
  {
    "Id": 5145,
    "Fornavn": "Aslak",
    "Etternavn": "Becke",
    "Kjonn": "Mann",
    "Alder": 48,
    "ArbStedNr": "65850000",
    "Arbeidsted": "Stend vgs - Avd. Tilrettelagt",
    "ArbfNr": 2,
    "Ansattforhold": "Fast",
    "Stillingskode": "751708",
    "Stillingsbeskrivelse": "Miljøfagarbeidar sfo",
    "ArsLonn": 393500.0,
    "TilleggsSum": 0.0,
    "LonnProsent": 29.19,
    "KravTilbut": "False"
  }
]